# Generated by Django 4.0.6 on 2023-06-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_mymodel2'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=200)),
                ('type_your_message', models.TextField()),
            ],
        ),
    ]
